# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('Logo', models.CharField(max_length=1000)),
                ('Total', models.IntegerField()),
                ('Serial_number', models.IntegerField()),
            ],
        ),
    ]
