# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-01 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='Logo',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='Serial_number',
            new_name='Serial_Number',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='Total',
            new_name='Total_for_that_chapter',
        ),
    ]
